### ISSUE TITLE
Flow API token use is deprecated now.

### ISSUE THREAD

**Issue by thadguidry** [c3tp/jenkins-flowdock-notifier#1]
The flow API token is deprecated and the Messages endpoint should be used instead.  - according to new Flowdock API documentation.

It seems that only OAuth 2.0 and HTTP Basic Authentication are supported now ?
https://www.flowdock.com/account/tokens

REFERENCE: https://github.com/flowdock/api-docs/pull/67

**Comment by dleske** [comment]
Agreed.  However this is a stopgap since the Flowdock plugin is out of date, as mentioned in the README.  Rather than update this notifier script, I would prefer the Flowdock Jenkins plugin was updated for (1) the new endpoint and (2) Pipeline integration.

**Comment by thadguidry** [comment]
:+1:  @dleske
